name: CI

on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Lint
        run: npm run lint
      - name: Build artifact
        run: npm run cdk:synth
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: cdk.out
          path: cdk.out

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: cdk.out
      - name: Deploy
        run: npx cdk deploy --app cdk.out --require-approval never
